In [1]:
import glob
import numpy as np
import pandas as pd
import pickle

data_dir = "../../data/openFDA_drug_event/"
er_dir = data_dir+'er_tables_memory_efficient/'

In [2]:
primarykey='safetyreportid'

In [3]:
patients = pd.read_csv(er_dir+'patient.csv.gz',
                       compression='gzip',
                       dtype={
                           'safetyreportid' : 'str',
                           'patient_custom_master_age' : 'float'
                       })

In [4]:
report = (pd.read_csv(er_dir+'report.csv.gz',
                      compression='gzip',
                     dtype={
                         'safetyreportid' : 'str'
                     }))
report.head()

  safetyreportid  lastupdate_date  mostrecent_receive_date  receive_date
0       10003300         20141002                 20140306      20140306
1       10003301         20141002                 20140228      20140228
2       10003302         20141002                 20140312      20140312
3       10003304         20141212                 20140424      20140312
4       10003305         20141002                 20140312      20140312

In [9]:
patients_merge = patients.merge(report, on='safetyreportid', how='inner')
patients_merge.head()

,patient_custom_master_age,patient_onsetage,patient_onsetageunit,patient_sex,patient_weight,safetyreportid,lastupdate_date,mostrecent_receive_date,receive_date
0,77.0,77.0,Year,Female,NaN,10003300,20141002,20140306,20140306
1,NaN,NaN,NaN,Female,NaN,10003301,20141002,20140228,20140228
2,NaN,NaN,NaN,Male,NaN,10003302,20141002,20140312,20140312
3,NaN,NaN,NaN,Female,NaN,10003304,20141212,20140424,20140312
4,48.0,48.0,Year,Female,NaN,10003305,20141002,20140312,20140312

In [10]:
report_serious = pd.read_csv(er_dir+'report_serious.csv.gz',compression='gzip')
report_serious.head()

/tmp/ipykernel_15437/1096606733.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  report_serious = pd.read_csv(er_dir+'report_serious.csv.gz',compression='gzip')

,congenital_anomali,death,disabling,hospitalization,life_threatening,other,safetyreportid,serious
0,NaN,NaN,1.0,NaN,NaN,NaN,10003300,"The adverse event resulted in death, a life th..."
1,NaN,NaN,NaN,NaN,NaN,1.0,10003301,"The adverse event resulted in death, a life th..."
2,NaN,NaN,NaN,NaN,NaN,NaN,10003302,The adverse event did not result in any of the...
3,NaN,NaN,NaN,NaN,NaN,NaN,10003304,The adverse event did not result in any of the...
4,NaN,NaN,NaN,NaN,NaN,NaN,10003305,The adverse event did not result in any of the...

In [13]:
patients_merge = patients_merge.merge(report_serious, on='safetyreportid', how='inner')
patients_merge.head()

,patient_custom_master_age,patient_onsetage,patient_onsetageunit,patient_sex,patient_weight,safetyreportid,lastupdate_date,mostrecent_receive_date,receive_date,congenital_anomali,death,disabling,hospitalization,life_threatening,other,serious
0,NaN,NaN,NaN,Male,NaN,25104699,20250409,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...
1,NaN,NaN,NaN,Female,NaN,25104700,20250409,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...
2,NaN,NaN,NaN,Female,NaN,25104701,20250409,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...
3,89.0,89.0,Year,Female,NaN,25104702,20250409,20250321,20250321,NaN,NaN,NaN,NaN,NaN,1.0,"The adverse event resulted in death, a life th..."
4,NaN,NaN,NaN,Female,NaN,25104703,20250408,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...

In [14]:
reporter = pd.read_csv(er_dir+'reporter.csv.gz',compression='gzip')
reporter.head()

/tmp/ipykernel_15437/3456334972.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  reporter = pd.read_csv(er_dir+'reporter.csv.gz',compression='gzip')

,reporter_company,reporter_country,reporter_qualification,safetyreportid
0,1289378,US,Consumer or non-health professional,10003300
1,US-JNJFOC-20130719067,US,Consumer or non-health professional,10003301
2,US-PFIZER INC-2014068976,US,Consumer or non-health professional,10003302
3,US-PFIZER INC-2014063856,US,Physician,10003304
4,US-PFIZER INC-2014069067,US,Physician,10003305

In [15]:
patients_merge = patients_merge.merge(reporter, on='safetyreportid', how='inner')
patients_merge.head()

,patient_custom_master_age,patient_onsetage,patient_onsetageunit,patient_sex,patient_weight,safetyreportid,lastupdate_date,mostrecent_receive_date,receive_date,congenital_anomali,death,disabling,hospitalization,life_threatening,other,serious,reporter_company,reporter_country,reporter_qualification
0,NaN,NaN,NaN,Male,NaN,25104699,20250409,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...,"US-AZURITY PHARMACEUTICALS, INC.-US-2024AZR000423",US,Other health professional
1,NaN,NaN,NaN,Female,NaN,25104700,20250409,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...,"US-AZURITY PHARMACEUTICALS, INC.-US-2024AZR000515",US,Consumer or non-health professional
2,NaN,NaN,NaN,Female,NaN,25104701,20250409,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...,"US-AZURITY PHARMACEUTICALS, INC.-US-2024AZR000719",US,Other health professional
3,89.0,89.0,Year,Female,NaN,25104702,20250409,20250321,20250321,NaN,NaN,NaN,NaN,NaN,1.0,"The adverse event resulted in death, a life th...",JP-JNJFOC-20250362035,JP,Physician
4,NaN,NaN,NaN,Female,NaN,25104703,20250408,20250321,20250321,2.0,2.0,2.0,2.0,2.0,2.0,The adverse event did not result in any of the...,US-ELI_LILLY_AND_COMPANY-US202503018549,US,Consumer or non-health professional

In [16]:
patients_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3145728 entries, 0 to 3145727
Data columns (total 19 columns):
 #   Column                     Dtype
---  ------                     -----
 0   patient_custom_master_age  float64
 1   patient_onsetage           float64
 2   patient_onsetageunit       object
 3   patient_sex                object
 4   patient_weight             float64
 5   safetyreportid             object
 6   lastupdate_date            int64
 7   mostrecent_receive_date    int64
 8   receive_date               int64
 9   congenital_anomali         float64
 10  death                      float64
 11  disabling                  float64
 12  hospitalization            float64
 13  life_threatening           float64
 14  other                      float64
 15  serious                    object
 16  reporter_company           object
 17  reporter_country           object
 18  reporter_qualification     object
dtypes: float64(9), int64(3), object(7)
memory usage: 456.0+ MB

In [17]:
drug_characteristics_df = pd.read_csv('../../data/openFDA_drug_event/er_tables_memory_efficient/drugcharacteristics.csv.gz',compression='gzip')

/tmp/ipykernel_15437/195607322.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  drug_characteristics_df = pd.read_csv('../../data/openFDA_drug_event/er_tables_memory_efficient/drugcharacteristics.csv.gz',compression='gzip')

In [18]:
reaction_df = pd.read_csv("../../data/openFDA_drug_event/er_tables_memory_efficient/reactions.csv.gz", compression='gzip', low_memory=False)

In [19]:
patients_merge = patients_merge.merge(drug_characteristics_df, on='safetyreportid', how='inner')

In [20]:
patients_merge = patients_merge.merge(reaction_df, on='safetyreportid', how='inner')

In [21]:
patients_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50083154 entries, 0 to 50083153
Data columns (total 25 columns):
 #   Column                     Dtype
---  ------                     -----
 0   patient_custom_master_age  float64
 1   patient_onsetage           float64
 2   patient_onsetageunit       object
 3   patient_sex                object
 4   patient_weight             float64
 5   safetyreportid             object
 6   lastupdate_date            int64
 7   mostrecent_receive_date    int64
 8   receive_date               int64
 9   congenital_anomali         float64
 10  death                      float64
 11  disabling                  float64
 12  hospitalization            float64
 13  life_threatening           float64
 14  other                      float64
 15  serious                    object
 16  reporter_company           object
 17  reporter_country           object
 18  reporter_qualification     object
 19  drug_administration        object
 20  drug_characterization      object
 21  drug_indication            object
 22  medicinal_product          object
 23  reaction_meddrapt          object
 24  reaction_outcome           object
dtypes: float64(9), int64(3), object(13)
memory usage: 9.3+ GB

In [22]:
patients_merge.to_csv('../../data/patients_drug_reaction_report_full.csv', index=False)

In [23]:
sampled_data = patients_merge.sample(n=1000, random_state=42)

print("sampling 1,000 row:")
print("\nnumber of row and column:", sampled_data.shape)
print("\ncolumns:", sampled_data.columns.tolist())
display(sampled_data.head(10))


sampled_data.to_csv('../../data/sampled_full_data.csv', index=False)
sampled_data.to_excel('../../data/sampled_full_data.xlsx', index=False)

sampling 1,000 row:

number of row and column: (1000, 25)

columns: ['patient_custom_master_age', 'patient_onsetage', 'patient_onsetageunit', 'patient_sex', 'patient_weight', 'safetyreportid', 'lastupdate_date', 'mostrecent_receive_date', 'receive_date', 'congenital_anomali', 'death', 'disabling', 'hospitalization', 'life_threatening', 'other', 'serious', 'reporter_company', 'reporter_country', 'reporter_qualification', 'drug_administration', 'drug_characterization', 'drug_indication', 'medicinal_product', 'reaction_meddrapt', 'reaction_outcome']

,patient_custom_master_age,patient_onsetage,patient_onsetageunit,patient_sex,patient_weight,safetyreportid,lastupdate_date,mostrecent_receive_date,receive_date,congenital_anomali,...,serious,reporter_company,reporter_country,reporter_qualification,drug_administration,drug_characterization,drug_indication,medicinal_product,reaction_meddrapt,reaction_outcome
3560768,49.0,49.0,Year,Female,72.5755,4548952-3,20050727,20041013,20041227,NaN,...,The adverse event did not result in any of the...,04P-1623-0277151-00,NaN,Consumer or non-health professional,NaN,Concomitant (the drug was reported as being ta...,NaN,MELOXICAM,DEPENDENCE,NaN
45730692,81.0,81.0,Year,Female,71.2200,8335193-7,20120825,20120420,20120503,NaN,...,"The adverse event resulted in death, a life th...",US-MYLANLABS-2009AL000589,UNITED STATES,Consumer or non-health professional,NaN,Concomitant (the drug was reported as being ta...,NaN,LASIX,FEELING ABNORMAL,NaN
37682359,NaN,NaN,NaN,Male,NaN,7656053-0,20111222,20110722,20110804,NaN,...,"The adverse event resulted in death, a life th...",CA-ELI_LILLY_AND_COMPANY-CA201107006131,CANADA,Physician,NaN,Concomitant (the drug was reported as being ta...,NaN,SEROQUEL,INTRA-ABDOMINAL HAEMATOMA,NaN
3198502,51.0,51.0,Year,Female,65.0000,4515198-4,20050328,20041025,20041201,NaN,...,"The adverse event resulted in death, a life th...",JP-GLAXOSMITHKLINE-B0349721A,NaN,Physician,Intravenous (not otherwise specified),Suspect (the drug was considered by the report...,NaN,ZANTAC,HYPOTENSION,NaN
31838028,15.0,15.0,Year,Male,NaN,7138749-2,20110411,20101110,20101122,NaN,...,"The adverse event resulted in death, a life th...",2009AC000340,UNITED STATES,NaN,NaN,Concomitant (the drug was reported as being ta...,NaN,ANCEF,ABDOMINAL PAIN,NaN
5571542,51.0,51.0,Year,Male,118.0000,4714537-9,20060218,20030407,20050714,NaN,...,"The adverse event resulted in death, a life th...",US-MERCK-0304USA00753,UNITED STATES,Physician,Unknown,Concomitant (the drug was reported as being ta...,NaN,ACIPHEX,PYREXIA,NaN
47748938,61.0,61.0,Year,Female,58.0000,8469779-6,20120825,20120621,20120626,NaN,...,"The adverse event resulted in death, a life th...",US-MERCK-1108USA02947,UNITED STATES,Physician,Unknown,Concomitant (the drug was reported as being ta...,NaN,VITAMIN E,TOOTH DISORDER,NaN
43641327,NaN,NaN,NaN,Female,NaN,8179702-X,20120608,20120221,20120302,NaN,...,"The adverse event resulted in death, a life th...",US-ELI_LILLY_AND_COMPANY-US201008003854,UNITED STATES,Physician,NaN,Concomitant (the drug was reported as being ta...,NaN,ZANTAC,CARDIAC ENZYMES INCREASED,NaN
32344154,NaN,NaN,NaN,Female,NaN,7201184-2,20110411,20101222,20101229,NaN,...,"The adverse event resulted in death, a life th...",US-CELGENEUS-163-21880-10110953,UNITED STATES,Physician,Unknown,Concomitant (the drug was reported as being ta...,DEPRESSION,LEXAPRO,DEATH,NaN
13549705,8.0,8.0,Year,Female,26.0000,5393830-3,20080115,20070719,20070719,NaN,...,"The adverse event resulted in death, a life th...",NaN,UNITED STATES,Pharmacist,NaN,Concomitant (the drug was reported as being ta...,NaN,CREON,CONDITION AGGRAVATED,NaN